// @ts-ignore — generated by `opennextjs-cloudflare build`
import handler from "./.open-next/worker.js";

const COMPRESSIBLE_RE =
  /^(text\/(html|css|javascript|plain|xml)|application\/(javascript|json|xml)|image\/svg\+xml)/;

export default {
  async fetch(request: Request, env: unknown, ctx: unknown): Promise<Response> {
    const response = await handler.fetch(request, env, ctx);

    const ae = request.headers.get("accept-encoding") ?? "";
    if (!ae.includes("gzip")) return response;

    if (
      !response.body ||
      response.headers.get("content-encoding") ||
      !COMPRESSIBLE_RE.test(response.headers.get("content-type") ?? "")
    ) {
      return response;
    }

    try {
      const { readable, writable } = new CompressionStream("gzip");
      response.body.pipeTo(writable).catch(() => {});
      const headers = new Headers(response.headers);
      headers.set("content-encoding", "gzip");
      headers.delete("content-length");
      const vary = headers.get("vary");
      headers.set("vary", vary ? `${vary}, accept-encoding` : "accept-encoding");
      const init = { status: response.status, statusText: response.statusText, headers };
      (init as any).encodeBody = "manual";
      return new Response(readable, init);
    } catch {
      return response;
    }
  },
};
